services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=developer_portal'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=developer_portal'
    ports:
      - '5432'
