spring:
  application:
    name: "developer-portal"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.elsevier.com/realms/platform
  jpa:
    hibernate:
      ddl-auto: "validate"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db

logging:
  structured:
    format:
      console: ecs
  level:
    com.media.portal: DEBUG


