spring:
  application:
    name: "developer-portal"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.elsevier.com/realms/platform
  jpa:
    hibernate:
      ddl-auto: "validate"

logging:
  structured:
    format:
      console: ecs
  level:
    com.media.portal: DEBUG


