security:
  oauth2:
    resourceserver:
      jwt:
        public-key-location: classpath:jwt-public.pem

management:
  newrelic:
    metrics:
      export:
        enabled: false

logging:
  structured:
    format:
      console: ""
  level:
    com.media.portal: DEBUG
